export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL    = 'FACEBOOK_LOGIN_FAIL';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_INSIDE_CART = 'REMOVE_ITEM_INSIDE_CART';
export const REMOVE_ALL_ITEM_INSIDE_CART = 'REMOVE_ALL_ITEM_INSIDE_CART';

